[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# For SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200